import re

ABBREVIATIONS = {
    "afaik": "as far as I know",
    "brb": "be right back",
    "btw": "by the way",
    "idk": "I don't know",
    "idc": "I don't care",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "jk": "just kidding",
    "lmk": "let me know",
    "nvm": "never mind",
    "omg": "oh my god",
    "tbh": "to be honest",
    "ttyl": "talk to you later",
    "yw": "you're welcome",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "bae": "before anyone else",
    "rofl": "rolling on the floor laughing",
    "smh": "shaking my head",
    "fomo": "fear of missing out",
    "yolo": "you only live once",
    "wtf": "what the fuck",
    "wth": "what the heck",
    "ffs": "for fuck's sake",
    "tl": "timeline",
    "nsfw": "not safe for work",
    "sfw": "safe for work",
    "fyp": "for you page",
    "ama": "ask me anything",
    "rng": "random number generator",
    "afk": "away from keyboard",
    "fyi": "for your information",
    "wip": "work in progress",
    "eod": "end of day",
    "tba": "to be announced",
    "tbd": "to be determined",
    "diy": "do it yourself",
    "ootd": "outfit of the day",
    "sec": "second",
    "min": "minute",
    "hr": "hour",
    "mil": "mother in law",
    "sil": "sister in law",
    "bil": "brother in law",
    "fil": "father in law",
    "ex-mil": "ex mother in law",
    "ex-fil": "ex father in law",
    "ex-bil": "ex brother in law",
    "ex-sil": "ex sister in law",
    "tifu": "today I fricked up",
}

CURSE_WORDS = {
    "fuck": "frick",
    "fucker": "fricker",
    "fucked": "fricked",
    "fucking": "fricking",
    "shit": "poop",
    "shitty": "poopy",
    "damn": "darn",
    "hell": "heck",
    "bitch": "witch",
    "bastard": "rascal",
    "ass": "butt",
    "asshole": "jerk",
    "dick": "jerk",
    "piss": "pee",
    "pissed": "peeved",
    "having sex": "making love",
    "have sex": "make love",
}

PATTERN = re.compile(
    r'\b(' + '|'.join(re.escape(abbr) for abbr in ABBREVIATIONS) + r')\b',
    re.IGNORECASE
)

CURSE_WORDS_PATTERN = re.compile(
    r'\b(' + '|'.join(re.escape(word) for word in CURSE_WORDS) + r')\b',
    re.IGNORECASE
)